server:
  port: 8082

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommicro
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    cloud:
      discovery:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
  file:
    name: D:/Eclipse Workspace/ecomm/cart/log/cart-service.log

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus,  resilience4j.circuitbreakers
  endpoint:
    health:
      show-details: always

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      productServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2